program: train.py
method: grid
project: FSCIT
name: tuning3_adapter
metric:
  goal: maximize
  name: session_max_acc
parameters:
  exp_name:
    value: baseline_10way10shot_finetune_base_inc_frozen
  update_base_classifier_with_prototypes:
    values: [True, False]
  start_training_with_prototypes:
    values: [True]
  epochs_base:
    values: [5, 10, 15]
  moco_loss_factor:
    value: 1.0
  lr_base:
    values: [0.001]
  encoder_ft_start_layer:
    values: [-1, 1, 6, 9, 12]
  adapt_blocks:
    values: [1, 3, 5]
  pet_cls:
    values: [Prefix, Adapter, LoRA]
  num_seeds:
    value: 3
  encoder_lr_factor:
    values: [0.5, 1, 2]
  encoder_ft_start_epoch:
    values: [0, 1, 5]
  pre_trained_url:
    value: https://storage.googleapis.com/vit_models/imagenet21k/ViT-B_16.npz
  shot:
    value: 10
  way:
    value: 10
  base_class:
    value: 10
