program: train.py
method: grid
project: FSCIT
name: baseline
metric:
  goal: maximize
  name: session_max_acc
parameters:
  exp_name:
    value: cap_incft
  update_base_classifier_with_prototypes:
    value: False
  start_training_with_prototypes:
    value: True
  epochs_base:
    value: 50
  moco_loss_factor:
    value: 1.0
  num_seeds:
    value: 3
  shot:
    value: 10
  result_key:
    value: cap_incft
  adapt_blocks:
    value: 12
  num_views:
    value: 2
  pet_cls:
    value: LoRA
  incft:
    value: True
  incft_layers:
    values: [classifier, classifier+pet]
  epochs_incremental:
    values: [0, 1, 5, 10]
  inc_ft_lr_factor:
    values: [0.1, 0.01]
  ce_loss_factor_incft:
    values: [0.5, 1.0]
  hf_model_checkpoint:
    values: [google/vit-base-patch16-224-in21k]
  dataset:
    values:
      [
        caltech101,
        cifar100,
        country211,
        cub200,
        dtd,
        eurosat,
        fgvc_aircraft,
        food101,
        gtsrb,
        mini_imagenet,
        oxford_flowers,
        oxford_pets,
        resisc45,
        stanford_cars,
        voc2007,
        sun397,
      ]
