# trunk-ignore-all(checkov/CKV2_GHA_1)
name: Static code checks

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  run-code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: precommit checker
        uses: pre-commit/action@v3.0.0
